/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_devops_demo_jni_bindings_SinusGenerator */

#ifndef _Included_net_devops_demo_jni_bindings_SinusGenerator
#define _Included_net_devops_demo_jni_bindings_SinusGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_devops_demo_jni_bindings_SinusGenerator
 * Method:    cppOpenMp
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_devops_demo_jni_bindings_SinusGenerator_cppOpenMp
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_devops_demo_jni_bindings_SinusGenerator
 * Method:    cppSequential
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_devops_demo_jni_bindings_SinusGenerator_cppSequential
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
