/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_devops_demo_jni_bindings_MassiveComputation */

#ifndef _Included_net_devops_demo_jni_bindings_MassiveComputation
#define _Included_net_devops_demo_jni_bindings_MassiveComputation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_devops_demo_jni_bindings_MassiveComputation
 * Method:    cppOpenMp
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_devops_demo_jni_bindings_MassiveComputation_cppOpenMp
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     net_devops_demo_jni_bindings_MassiveComputation
 * Method:    cppSequential
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_devops_demo_jni_bindings_MassiveComputation_cppSequential
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
