/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_devops_demo_jni_bindings_HelloWorldJni */

#ifndef _Included_net_devops_demo_jni_bindings_HelloWorldJni
#define _Included_net_devops_demo_jni_bindings_HelloWorldJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_devops_demo_jni_bindings_HelloWorldJni
 * Method:    parallel
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_devops_demo_jni_bindings_HelloWorldJni_parallel
  (JNIEnv *, jobject);

/*
 * Class:     net_devops_demo_jni_bindings_HelloWorldJni
 * Method:    array
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_devops_demo_jni_bindings_HelloWorldJni_array
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
